version: '3.7'

services:
  clueboys-client:
    image: benbergstein/zap-clueboys-client:latest
    environment:
      - PORT=3000
    depends_on:
      - server

  server:
    image: benbergstein/zap-server:latest
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - SECRET
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./server/data/production/postgres:/var/lib/postgresql/data

volumes:
  node_modules:
