version: '3.7'

services:
  clueboys-client:
    image: benbergstein/zap-clueboys-client:latest
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./clueboys-client:/app
      - node_modules2:/app/node_modules
    command: ["dev"]
    environment:
      - PORT=3000
      - SERVER_URL
      - CLIENT_URL
    depends_on:
      - server

  server:
    image: benbergstein/zap-server:latest
    ports:
      - ${PORT}:3000
    command: ["start:dev"]
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - SECRET
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./server/data/postgres:/var/lib/postgresql/data

volumes:
  node_modules:
  node_modules2:
  # app:
  #   image: 'benbergstein/bread:latest'
  #   ports:
  #     - "9000:3000"
  #   volumes:
  #     - ./:/app
