version: '3.7'

services:
  server:
    image: benbergstein/zap-server:latest
    ports:
      - ${PORT}:${PORT}
    command: ["start:dev"]
    environment:
      - PORT
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # app:
  #   image: 'benbergstein/bread:latest'
  #   ports:
  #     - "9000:3000"
  #   volumes:
  #     - ./:/app
